/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adraffy;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import org.json.JSONArray;
import io.github.adraffy.ens.ENSNormalize;
import io.github.adraffy.ens.InvalidLabelException;
import org.json.JSONObject;

public class Main {

    public static void main(String[] args) throws IOException {
        JSONArray recs = new JSONArray();
        System.out.println(ENSNormalize.NF.unicodeVersion);
        for (Object temp: new JSONArray(new String(Files.readAllBytes(Paths.get("../../../ens-labels/labels.json")), StandardCharsets.UTF_8))) {
            JSONObject rec = new JSONObject();
            String name = temp.toString();
            try {
                String norm = ENSNormalize.ENSIP15.normalize(name);
                if (!norm.equals(name)) {
                    rec.put("norm", norm);
                }
            } catch (InvalidLabelException err) {
                rec.put("error", err.getError().getMessage());
            }
            recs.put(rec);
        }   
        Files.write(Paths.get("../../output/java.json"), recs.toString().getBytes(StandardCharsets.UTF_8));
    }
}
